### ISSUE TITLE
TypeError: _prepare_mock() argument after ** must be a mapping, not tuple

### ISSUE THREAD

**Issue by alunduil** [racker/torment#81]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/tornado/testing.py", line 120, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/torment/contexts/__init__.py", line 80, in case
    fixture._execute()
  File "/usr/lib64/python3.4/site-packages/torment/fixtures/__init__.py", line 245, in _execute
    self.setup()
  File "/usr/lib64/python3.4/site-packages/torment/fixtures/__init__.py", line 428, in setup
    _prepare_mock(self.context, mock_symbol, **mock_result)
nose.proxy.TypeError: _prepare_mock() argument after ** must be a mapping, not tuple
```

Seems we should be checking if the magic should be happening a little closer.  Sometimes it should be bypassed without incident.

**Comment by alunduil** [comment]
Also part of this issue is the handling of leading underscores.  We do not currently handle symbols like ``_foo`` correctly.
